name: CI-CD

on:
  push:
    branches: master

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@master
    - name: setup node
      uses: actions/setup-node@v1
      with:
        version: 10
    
    - name: npm install & build
      run: |
        npm install
        npm install --global @gridsome/cli gh-pages
        gridsome build

    - name: deploy
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BRANCH: gh-pages
        FOLDER: dist
